// Generated by gencpp from file working_with_msgs/MyMsg.msg
// DO NOT EDIT!


#ifndef WORKING_WITH_MSGS_MESSAGE_MYMSG_H
#define WORKING_WITH_MSGS_MESSAGE_MYMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace working_with_msgs
{
template <class ContainerAllocator>
struct MyMsg_
{
  typedef MyMsg_<ContainerAllocator> Type;

  MyMsg_()
    : id(0)
    , message()  {
    }
  MyMsg_(const ContainerAllocator& _alloc)
    : id(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::working_with_msgs::MyMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::working_with_msgs::MyMsg_<ContainerAllocator> const> ConstPtr;

}; // struct MyMsg_

typedef ::working_with_msgs::MyMsg_<std::allocator<void> > MyMsg;

typedef boost::shared_ptr< ::working_with_msgs::MyMsg > MyMsgPtr;
typedef boost::shared_ptr< ::working_with_msgs::MyMsg const> MyMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::working_with_msgs::MyMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::working_with_msgs::MyMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace working_with_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'working_with_msgs': ['/home/turtlebot/ros_workspace/src/working_with_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::working_with_msgs::MyMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::working_with_msgs::MyMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::working_with_msgs::MyMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::working_with_msgs::MyMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::working_with_msgs::MyMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::working_with_msgs::MyMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::working_with_msgs::MyMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "073ce03da3ba6ba2c19723384f1df5d4";
  }

  static const char* value(const ::working_with_msgs::MyMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x073ce03da3ba6ba2ULL;
  static const uint64_t static_value2 = 0xc19723384f1df5d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::working_with_msgs::MyMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "working_with_msgs/MyMsg";
  }

  static const char* value(const ::working_with_msgs::MyMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::working_with_msgs::MyMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n\
string message\n\
";
  }

  static const char* value(const ::working_with_msgs::MyMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::working_with_msgs::MyMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::working_with_msgs::MyMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::working_with_msgs::MyMsg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORKING_WITH_MSGS_MESSAGE_MYMSG_H
