#!/usr/bin/env python
import rospy
from std_msgs.msg import UInt32
from std_msgs.msg import String
    
def callback(data):
	#rospy.loginfo(rospy.get_caller_id() + "I heard %s", data.data)
	pass
        
def node_b():
	pub=rospy.Publisher('topic_b',UInt32,queue_size=10)
	rospy.Subscriber("topic_a", String, callback)
	rospy.init_node('node_b', anonymous=True)
	rate=rospy.Rate(10)
	while not rospy.is_shutdown():
		hello_str=10
		#rospy.loginfo(hello_str)
		pub.publish(hello_str)
		rate.sleep()
	rospy.spin()
   
if __name__ == '__main__':
	try:
		node_b()
	except rospy.ROSInterruptException:
		pass