#!/usr/bin/env python
import rospy
from std_msgs.msg import String
from std_msgs.msg import UInt32

def callback(data):
	#rospy.loginfo(rospy.get_caller_id()+"I heard %s",data.data)
	pass

def node_a():
	pub = rospy.Publisher('topic_a', String, queue_size=10)
	rospy.Subscriber("topic_b",UInt32,callback)
        rospy.init_node('node_a', anonymous=True)
        rate = rospy.Rate(10) # 10hz
        while not rospy.is_shutdown():
		hello_str = "Hello from Node A"
		#rospy.loginfo(hello_str)
           	pub.publish(hello_str)
          	rate.sleep()
	rospy.spin()
   
if __name__ == '__main__':
	try:
		node_a()
	except rospy.ROSInterruptException:
		pass
